import Head from "next/head";
import About from "../src/components/About";
import Header from "../src/components/Header";
import MainContent from "../src/components/MainContent";
import Portfolio from "../src/components/Portfolio";
import Skills from "../src/components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MainContent />
        <About />
        <Skills />
        <Portfolio />
      </main>
    </div>
  );
}
